inherit_gem:
  rubocop-nosolosoftware:
    - rubocop-default.yml
    - rubocop-rake.yml
    - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "**/bin/**/*"

Layout/HeredocIndentation:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
