inherit_gem:
  rubocop-nosolosoftware:
    - rubocop-default.yml
    - rubocop-rake.yml
    - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.6.5

Layout/HeredocIndentation:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
